package com.etherfirma.mva.faa

data class FAAChart (
    var abbr: String,
    var facility: String,
    var prefix: String,
) {
    val url: String
        get () = "https://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/mva_mia/aixm/${prefix}.xml"
}

object FAA {
    object URL {
        val MVA = "https://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/mva_mia/mva/";
        val MIA = "https://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/mva_mia/mia/";
    }

    fun getMva () = MVA_DATA
    fun getMia () = MIA_DATA
}

private val MIA_DATA = listOf (
    FAAChart ("ZAB", "Albuquerque ARTCCC", "ZAB_TAV_2020"),
    FAAChart ("ZAN","Anchorage ARTCC","ZAN_TAV_2020"),
    FAAChart ("ZAU","Chicago ARTCC","ZAU_TAV_2019"),
    FAAChart ("ZBW","Boston ARTCC","ZBW_TAV_2020"),
    FAAChart ("ZDC","Washington ARTCC","ZDC_TAV_2020"),
    FAAChart ("ZDV","Denver ARTCC","ZDV_TAV_2020"),
    FAAChart ("ZFW","Fort Worth ARTCC","ZFW_TAV_2020"),
    FAAChart ("ZHN","Honolulu Control Facility","ZHN_TAV_2020"),
    FAAChart ("ZHU","Houston ARTCC","ZHU_TAV_2020"),
    FAAChart ("ZID","Indianappolis ARTCC","ZID_TAV_2018"),
    FAAChart ("ZJX","Jacksonville ARTCC","ZJX_TAV_2019"),
    FAAChart ("ZKC","Kansas City ARTCC","ZKC_TAV_2020"),
    FAAChart ("ZLA","Los Angeles ARTCC","ZLA_TAV_2019"),
    FAAChart ("ZLC","Salt Lake City ARTCC","ZLC_TAV_2018"),
    FAAChart ("ZMA","Miami ARTCC","ZMA_TAV_2020"),
    FAAChart ("ZSE","Seattle ARTCC","ZSE_TAV_2020"),
    FAAChart ("ZSU","San Juan ARTCC","ZSU_TAV_2018"),
    FAAChart ("ZME","Memphis ARTCC","ZME_TAV_2019"),
    FAAChart ("ZMP","Minneapolis ARTCC","ZMP_TAV_2020"),
    FAAChart ("ZNY","New York ARTCC","ZNY_TAV_2019"),
    FAAChart ("ZOA","Oakland ARTCC","ZOA_TAV_2020"),
    FAAChart ("ZTL","Atlanta ARTCC","ZTL_TAV_202"),
)

private val MVA_DATA = listOf (
    FAAChart ("A11", "Anchorage TRACON", "A11_MVA_FUS3_2019"),
    FAAChart ("A11", "Anchorage TRACON", "A11_MVA_FUS5_2019"),
    FAAChart ("A80", "Atlanta TRACON", "A80_MVA_FUS3_2020"),
    FAAChart ("A80", "Atlanta TRACON", "A80_MVA_FUS5_2019"),
    FAAChart ("A90", "Boston Consolidated TRACON", "A90_MVA_FUS3_2020"),
    FAAChart ("A90", "Boston Consolidated TRACON", "A90_MVA_FUS5_2019"),
    FAAChart ("ABE", "Allentown ATCT/TRACON", "ABE_MVA_FUS3_2020"),
    FAAChart ("ABE", "Allentown ATCT/TRACON", "ABE_MVA_FUS5_2020"),
    FAAChart ("ABI", "Abilene ATCT/TRACON", "ABI_MVA_FUS3_2020"),
    FAAChart ("ABI", "Abilene ATCT/TRACON", "ABI_MVA_FUS5_2020"),
    FAAChart ("ABQ", "Albuquerque ATCT/TRACON", "ABQ_MVA_FUS3_2020"),
    FAAChart ("ABQ", "Albuquerque ATCT/TRACON", "ABQ_MVA_FUS5_2020"),
    FAAChart ("ACT", "Waco ATCT/TRACON", "ACT_ACT_MVA_2019"),
    FAAChart ("ACT", "Waco ATCT/TRACON", "ACT_MVA_FUS3_2019"),
    FAAChart ("ACT", "Waco ATCT/TRACON", "ACT_MVA_FUS5_2019"),
    FAAChart ("ACY", "Atlantic City ATCT/TRACON", "ACY_MVA_FUS3_2019"),
    FAAChart ("ACY", "Atlantic City ATCT/TRACON", "ACY_MVA_FUS5_2019"),
    FAAChart ("AGS", "Augusta ATCT/TRACON", "AGS_MVA_FUS3_2018"),
    FAAChart ("ALB", "Albany ATCT/TRACON", "ALB_MVA_FUS3_2020"),
    FAAChart ("ALB", "Albany ATCT/TRACON", "ALB_MVA_FUS5_2020"),
    FAAChart ("ALO", "Waterloo ATCT/TRACON", "ALO_MVA_FUS3_2019"),
    FAAChart ("ALO", "Waterloo ATCT/TRACON", "ALO_MVA_FUS5_2019"),
    FAAChart ("AMA", "Amarillo ATCT/TRACON", "AMA_MVA_FUS3_2020"),
    FAAChart ("AMA", "Amarillo ATCT/TRACON", "AMA_MVA_FUS5_2020"),
    FAAChart ("ASE", "Aspen ATCT/TRACON", "ASE_MVA_FUS3_2020"),
    FAAChart ("ASE", "Aspen ATCT/TRACON", "ASE_MVA_FUS5_2020"),
    FAAChart ("AUS", "Austin ATCT/TRACON", "AUS_MVA_FUS3_2019"),
    FAAChart ("AUS", "Austin ATCT/TRACON", "AUS_MVA_FUS5_2019"),
    FAAChart ("AVL", "Asheville ATCT/TRACON", "AVL_MVA_FUS3_2020"),
    FAAChart ("AVL", "Asheville ATCT/TRACON", "AVL_MVA_FUS5_2020"),
    FAAChart ("AVP", "Wilkes-Barre ATCT/TRACON", "AVP_MVA_FUS3_2019"),
    FAAChart ("AVP", "Wilkes-Barre ATCT/TRACON", "AVP_MVA_FUS5_2019"),
    FAAChart ("AZO", "Kalamozoo ATCT/TRACON", "AZO_MVA_FUS3_2020"),
    FAAChart ("AZO", "Kalamozoo ATCT/TRACON", "AZO_MVA_FUS5_2020"),
    FAAChart ("BFL", "Bakersfield ATCT/TRACON", "BFL_MVA_FUS3_2019"),
    FAAChart ("BFL", "Bakersfield ATCT/TRACON", "BFL_MVA_FUS5_2019"),
    FAAChart ("BGM", "Bignhamton ATCT/TRACON", "BGM_MVA_FUS3_2020"),
    FAAChart ("BGM", "Bignhamton ATCT/TRACON", "BGM_MVA_FUS5_2020"),
    FAAChart ("BGR", "Bangor ATCT/TRACON", "BGR_MVA_FUS3_2019"),
    FAAChart ("BGR", "Bangor ATCT/TRACON- BGR_MVA_FUS5_2019"),
    FAAChart ("BHM", "Birmingham ATCT/TRACON", "BHM_MVA_FUS3_2020"),
    FAAChart ("BHM", "Birmingham ATCT/TRACON", "BHM_MVA_FUS5_2020"),
    FAAChart ("BIS", "Bismarck ATCT/TRACON", "BIS_MVA_FUS3_2020"),
    FAAChart ("BIS", "Bismarck ATCT/TRACON", "BIS_MVA_FUS5_2020"),
    FAAChart ("BNA", "Nashville ATCT/TRACON", "BNA_MVA_FUS3_2020"),
    FAAChart ("BNA", "Nashville ATCT/TRACON", "BNA_MVA_FUS5_2019"),
    FAAChart ("BOI", "Boise ATCT/TRACON", "BOI_MVA_FUS3_2019"),
    FAAChart ("BOI", "Boise ATCT/TRACON", "BOI_MVA_FUS5_2019"),
    FAAChart ("BTR", "Baton Rouge ATCT/TRACON", "BTR_MVA_FUS3_2020"),
    FAAChart ("BTR", "Baton Rouge ATCT/TRACON", "BTR_MVA_FUS5_2020"),
    FAAChart ("BTV", "Burlington ATCT/TRACON", "BTV_MVA_CENRAP_2020"),
    FAAChart ("BTV", "Burlington ATCT/TRACON", "BTV_MVA_FUS3_2020"),
    FAAChart ("BTV", "Burlington ATCT/TRACON", "BTV_MVA_FUS5_2020"),
    FAAChart ("BUF", "Buffalo ATCT/TRACON", "BUF_MVA_FUS3_2020"),
    FAAChart ("BUF", "Buffalo ATCT/TRACON", "BUF_MVA_FUS5_2019"),
    FAAChart ("C90", "Chicago TRACON", "C90_MVA_FUS3_2020"),
    FAAChart ("C90", "Chicago TRACON", "C90_MVA_FUS5_2020"),
    FAAChart ("CAE", "Columbia ATCT/TRACON", "CAE_MVA_FUS3_2018"),
    FAAChart ("CAE", "Columbia ATCT/TRACON", "CAE_MVA_FUS5_2018"),
    FAAChart ("CHA", "Chattanooga ATCT/TRACON", "CHA_MVA_FUS3_2019"),
    FAAChart ("CHA", "Chattanooga ATCT/TRACON", "CHA_MVA_FUS5_2019"),
    FAAChart ("CHS", "Charleston ATCT/TRACON", "CHS_MVA_FUS3_2019"),
    FAAChart ("CHS", "Charleston ATCT/TRACON", "CHS_MVA_FUS5_2019"),
    FAAChart ("CID", "Cedar Rapids ATCT/TRACON", "CID_MVA_FUS3_2018"),
    FAAChart ("CID", "Cedar Rapids ATCT/TRACON", "CID_MVA_FUS5_2019"),
    FAAChart ("CKB", "Clarksburg ATCT/TRACON", "CKB_MVA_FUS3_2019"),
    FAAChart ("CKB", "Clarksburg ATCT/TRACON", "CKB_MVA_FUS5_2018"),
    FAAChart ("CLE", "Cleveland ATCT/TRACON", "CLE_MVA_FUS3_2019"),
    FAAChart ("CLE", "Cleveland ATCT/TRACON", "CLE_MVA_FUS5_2019"),
    FAAChart ("CLT", "Charlotte ATCT/TRACON", "CLT_MVA_FUS3_2018"),
    FAAChart ("CLT", "Charlotte ATCT/TRACON", "CLT_MVA_FUS5_2018"),
    FAAChart ("CMH", "Columbus ATCT/TRACON", "CMH_MVA_FUS3_2020"),
    FAAChart ("CMH", "Columbus ATCT/TRACON", "CMH_MVA_FUS5_2020"),
    FAAChart ("CMI", "Willard ATCT/TRACON", "CMI_MVA_FUS3_2020"),
    FAAChart ("CMI", "Willard ATCT/TRACON", "CMI_MVA_FUS5_2020"),
    FAAChart ("COS", "Colorado Springs ATCT/TRACON", "COS_MVA_FUS3_2019"),
    FAAChart ("COS", "Colorado Springs ATCT/TRACON", "COS_MVA_FUS5_2019"),
    FAAChart ("CPR", "Casper ATCT/TRACON", "CPR_MVA_FUS3_2019"),
    FAAChart ("CPR", "Casper ATCT/TRACON", "CPR_MVA_FUS5_2019"),
    FAAChart ("CRP", "Corpus Cristi ATCT/TRACON", "CRP_MVA_FUS3_2019"),
    FAAChart ("CRP", "Corpus Cristi ATCT/TRACON", "CRP_MVA_FUS5_2019"),
    FAAChart ("CRW", "Charleston ATCT/TRACON", "CRW_MVA_FUS3_2019"),
    FAAChart ("CRW", "Charleston ATCT/TRACON", "CRW_MVA_FUS5_2019"),
    FAAChart ("CVG", "Greater Cincinnati ATCT/TRACON", "CVG_MVA_FUS3_2020"),
    FAAChart ("CVG", "Greater Cincinnati ATCT/TRACON", "CVG_MVA_FUS5_2020"),
    FAAChart ("D01", "Denver TRACON", "D01_MVA_FUS3_2018"),
    FAAChart ("D01", "Denver TRACON", "D01_MVA_FUS5_2018"),
    FAAChart ("D10", "Dallas-Fort Worth TRACON", "D10_MVA_FUS3_2020"),
    FAAChart ("D10", "Dallas-Fort Worth TRACON", "D10_MVA_FUS5_2020"),
    FAAChart ("D21", "Detroit TRACON", "D21_MVA_FUS3_2019"),
    FAAChart ("D21", "Detroit TRACON", "D21_MVA_FUS5_2019"),
    FAAChart ("DAB", "Daytona ATCT/TRACON DAB_MVA_FUS3_2020"),
    FAAChart ("DAB", "Daytona ATCT/TRACON DAB_MVA_FUS5_2020"),
    FAAChart ("DLH", "Duluth ATCT/TRACON", "DLH_MVA_FUS3_2020"),
    FAAChart ("DLH", "Duluth ATCT/TRACON", "DLH_MVA_FUS5_2020"),
    FAAChart ("DSM", "Des Moines ATCT/TRACON DSM_MVA_FUS3_2020"),
    FAAChart ("DSM", "Des Moines ATCT/TRACON DSM_MVA_FUS5_2020"),
    FAAChart ("ELM", "Elmira ATCT/TRACON", "ELM_MVA_FUS3_2020"),
    FAAChart ("ELM", "Elmira ATCT/TRACON", "ELM_MVA_FUS5_2020"),
    FAAChart ("ELM", "Elmira ATCT/TRACON", "ELP_MVA_FUS3_2020"),
    FAAChart ("ELM", "Elmira ATCT/TRACON", "ELP_MVA_FUS5_2020"),
    FAAChart ("EUG", "Eugene ATCT/TRACON", "EUG_MVA_FUS3_2020"),
    FAAChart ("EUG", "Eugene ATCT/TRACON", "EUG_MVA_FUS5_2019"),
    FAAChart ("EVV", "Evansville ATCT/TRACON", "EVV_MVA_FUS3_2020"),
    FAAChart ("EVV", "Evansville ATCT/TRACON", "EVV_MVA_FUS5_2020"),
    FAAChart ("F11", "Central Florida TRACON", "F11_MVA_FUS3_2020"),
    FAAChart ("F11", "Central Florida TRACON", "F11_MVA_FUS5_2020"),
    FAAChart ("FAI", "Fairbanks ATCT/TRACON", "FAI_MVA_FUS3_2020"),
    FAAChart ("FAI", "Fairbanks ATCT/TRACON", "FAI_MVA_FUS5_2020"),
    FAAChart ("FAR", "Fargo ATCT/TRACON", "FAR_MVA_FUS3_2020"),
    FAAChart ("FAR", "Fargo ATCT/TRACON", "FAR_MVA_FUS5_2020"),
    FAAChart ("FAT", "Fresno ATCT/TRACON", "FAT_MVA_FUS3_2019"),
    FAAChart ("FAT", "Fresno ATCT/TRACON", "FAT_MVA_FUS5_2019"),
    FAAChart ("FAY", "Fayetteville ATCT/TRACON", "FAY_FAY_MVA_2020"),
    FAAChart ("FAY", "Fayetteville ATCT/TRACON", "FAY_MVA_FUS5_2020"),
    FAAChart ("FLO", "Florence ATCT/TRACON", "FLO_MVA_FUS3_2019"),
    FAAChart ("FLO", "Florence ATCT/TRACON", "FLO_MVA_FUS5_2019"),
    FAAChart ("FNT", "Flint ATCT/TRACON", "FNT_FNT_MVA_2018"),
    FAAChart ("FSD", "Sioux Falls ATCT/TRACON", "FSD_MVA_FUS3_2019"),
    FAAChart ("FSD", "Sioux Falls ATCT/TRACON", "FSD_MVA_FUS5_2019"),
    FAAChart ("FSM", "Fort Smith ATCT/TRACON", "FSM_MVA_FUS3_2018"),
    FAAChart ("FSM", "Fort Smith ATCT/TRACON", "FSM_MVA_FUS5_2018"),
    FAAChart ("FWA", "Fort Wayne ATCT/TRACON", "FWA_MVA_FUS3_2019"),
    FAAChart ("FWA", "Fort Wayne ATCT/TRACON", "FWA_MVA_FUS5_2019"),
    FAAChart ("GEG", "Spokane ATCT/TRACON", "GEG_MSO_MVA_FUS3_2020"),
    FAAChart ("GEG", "Spokane ATCT/TRACON", "GEG_MSO_MVA_FUS5_2020"),
    FAAChart ("GEG", "Spokane ATCT/TRACON", "GEG_MVA_FUS3_2020"),
    FAAChart ("GEG", "Spokane ATCT/TRACON", "GEG_MVA_FUS5_2020"),
    FAAChart ("GEG", "Spokane ATCT/TRACON", "GGG_MVA_FUS3_2018"),
    FAAChart ("GEG", "Spokane ATCT/TRACON", "GGG_MVA_FUS5_2018"),
    FAAChart ("GPT", "Gulfport ATCT/TRACON", "GPT_MVA_FUS3_2019"),
    FAAChart ("GPT", "Gulfport ATCT/TRACON", "GPT_MVA_FUS5_2019"),
    FAAChart ("GRB", "Greenbay ATCT/TRACON", "GRB_MVA_FUS3_2019"),
    FAAChart ("GRB", "Greenbay ATCT/TRACON", "GRB_MVA_FUS5_2019"),
    FAAChart ("GSO", "Greensboro ATCT/TRACON", "GSO_MVA_FUS3_2019"),
    FAAChart ("GSO", "Greensboro ATCT/TRACON", "GSO_MVA_FUS5_2019"),
    FAAChart ("GSP", "Greer ATCT/TRACON", "GSP_MVA_FUS3_2020"),
    FAAChart ("GSP", "Greer ATCT/TRACON", "GSP_MVA_FUS5_2020"),
    FAAChart ("GTF", "Great Falls ATCT/TRACON", "GTF_MVA_FUS3_2019"),
    FAAChart ("GTF", "Great Falls ATCT/TRACON", "GTF_MVA_FUS5_2019"),
    FAAChart ("HLN", "Helena ATCT/TRACON", "HLN_MVA_VOR_2019"),
    FAAChart ("HLN", "Helena ATCT/TRACON", "HLN_MVA_MULTI_2019"),
    FAAChart ("HSV", "Huntsville ATCT/TRACON", "HSV_MVA_FUS3_2020"),
    FAAChart ("HSV", "Huntsville ATCT/TRACON", "HSV_MVA_FUS5_2020"),
    FAAChart ("HTS", "Huntington ATCT/TRACON", "HTS_MVA_FUS3_2020"),
    FAAChart ("HTS", "Huntington ATCT/TRACON", "HTS_MVA_FUS5_2020"),
    FAAChart ("HUF", "Terre Haute ATCT/TRACON", "HUF_MVA_FUS3_2019"),
    FAAChart ("HUF", "Terre Haute ATCT/TRACON", "HUF_MVA_FUS5_2019"),
    FAAChart ("I90", "Houston TRACON", "I90_MVA_FUS3_2020"),
    FAAChart ("I90", "Houston TRACON", "I90_MVA_FUS5_2018"),
    FAAChart ("ICT", "Wichita ATCT/TRACON", "ICT_MVA_FUS3_2020"),
    FAAChart ("ICT", "Wichita ATCT/TRACON", "ICT_MVA_FUS5_2020"),
    FAAChart ("ILM", "Wilmington ATCT/TRACON", "ILM_ILM_MVA_2019"),
    FAAChart ("ILM", "Wilmington ATCT/TRACON", "ILM_MVA_CENRAP_2019"),
    FAAChart ("IND", "Indianapolis ATCT/TRACON", "IND_MVA_FUS3_2020"),
    FAAChart ("IND", "Indianapolis ATCT/TRACON", "IND_MVA_FUS5_2020"),
    FAAChart ("JAN", "Jackson ATCT/TRACON", "JAN_MVA_FUS3_2020"),
    FAAChart ("JAN", "Jackson ATCT/TRACON", "JAN_MVA_FUS5_2020"),
    FAAChart ("JAX", "Jacksonville ATCT/TRACON", "JAX_MVA_FUS3_2019"),
    FAAChart ("JAX", "Jacksonville ATCT/TRACON", "JAX_MVA_FUS5_2019"),
    FAAChart ("JCF", "JOSHUA ATCT/TRACON", "JCF_EDW_MVA_2019"),
    FAAChart ("JCF", "JOSHUA ATCT/TRACON", "JCF_MVA_FUS5_2019"),
    FAAChart ("L30", "Las Vegas TRACON", "L30_LAS_MVA_2018"),
    FAAChart ("L30", "Las Vegas TRACON", "L30_MVA_FUS3_2018"),
    FAAChart ("L30", "Las Vegas TRACON", "L30_QAS_MVA_2020"),
    FAAChart ("LAN", "Lansing ATCT/TRACON", "LAN_LAN_MVA_2018"),
    FAAChart ("LBB", "Lubbuck ATCT/TRACON", "LBB_MVA_FUS3_2020"),
    FAAChart ("LBB", "Lubbuck ATCT/TRACON", "LBB_MVA_FUS5_2020"),
    FAAChart ("LCH", "Lake Charkes ATCT/TRACON", "LCH_MVA_FUS3_2020"),
    FAAChart ("LCH", "Lake Charkes ATCT/TRACON", "LCH_MVA_FUS5_2020"),
    FAAChart ("LEX", "Lexington ATCT/TRACON", "LEX_LEX_MVA_2018"),
    FAAChart ("LEX", "Lexington ATCT/TRACON", "LEX_MVA_CENRAP_2018"),
    FAAChart ("LFT", "Lafayette ATCT/TRACON", "LFT_MVA_FUS3_2019"),
    FAAChart ("LFT", "Lafayette ATCT/TRACON", "LFT_MVA_FUS5_2019"),
    FAAChart ("LIT", "Little Rock ATCT/TRACON", "LIT_MVA_FUS3_2018"),
    FAAChart ("LIT", "Little Rock ATCT/TRACON", "LIT_MVA_FUS5_2018"),
    FAAChart ("M03", "Memphis TRACON", "M03_MVA_FUS3_2019"),
    FAAChart ("M03", "Memphis TRACON", "M03_MVA_FUS5_2019"),
    FAAChart ("M98", "Minneapolis TRACON", "M98_MVA_FUS3_2020"),
    FAAChart ("M98", "Minneapolis TRACON", "M98_MVA_FUS5_2020"),
    FAAChart ("MAF", "Midland ATCT/TRACON", "MAF_MVA_FUS3_2020"),
    FAAChart ("MAF", "Midland ATCT/TRACON", "MAF_MVA_FUS5_2020"),
    FAAChart ("MBS", "Saginaw ATCT/TRACON", "MBS_MBS_MVA_2018"),
    FAAChart ("MBS", "Saginaw ATCT/TRACON", "MBS_MVA_CENRAP_2018"),
    FAAChart ("MCI", "Kansas City ATCT/TRACON", "MCI_MVA_FUS3_2020"),
    FAAChart ("MCI", "Kansas City ATCT/TRACON", "MCI_MVA_FUS5_2020"),
    FAAChart ("MDT", "Harrisburg ATCT/TRACON", "MDT_MVA_FUS3_2020"),
    FAAChart ("MDT", "Harrisburg ATCT/TRACON", "MDT_MVA_FUS5_2020"),
    FAAChart ("MFD", "Mansfield ATCT/TRACON", "MFD_MFD_MVA_2018"),
    FAAChart ("MGM", "Montgomery ATCT/TRACON", "MGM_MVA_FUS3_2019"),
    FAAChart ("MGM", "Montgomery ATCT/TRACON", "MGM_MVA_FUS5_2019"),
    FAAChart ("MIA", "Miami ATCT/TRACON", "MIA_MVA_FUS3_2020"),
    FAAChart ("MIA", "Miami ATCT/TRACON", "MIA_MVA_FUS5_2020"),
    FAAChart ("MKE", "Milwaukee ATCT/TRACON", "MKE_MVA_FUS3_2020"),
    FAAChart ("MKE", "Milwaukee ATCT/TRACON", "MKE_MVA_FUS5_2020"),
    FAAChart ("MKE", "Milwaukee ATCT/TRACON", "MKG_MKG_MVA_2018"),
    FAAChart ("MLI", "Quad City ATCT/TRACON", "MLI_MVA_FUS3_2021"),
    FAAChart ("MLI", "Quad City ATCT/TRACON", "MLI_MVA_FUS5_2021"),
    FAAChart ("MLU", "Monroe ATCT/TRACON", "MLU_MVA_MULTI_2018"),
    FAAChart ("MOB", "Mobile ATCT/TRACON", "MOB_MVA_FUS3_2019"),
    FAAChart ("MOB", "Mobile ATCT/TRACON", "MOB_MVA_FUS5_2019"),
    FAAChart ("MSN", "Madison ATCT/TRACON", "MSN_MSN_MVA_2020"),
    FAAChart ("MSN", "Madison ATCT/TRACON", "MSN_MVA_FUS3_2020"),
    FAAChart ("MSN", "Madison ATCT/TRACON", "MSN_MVA_FUS5_2020"),
    FAAChart ("MSY", "New Orleans Moissant ATCT/TRACON", "MSY_MVA_FUS3_2019"),
    FAAChart ("MSY", "New Orleans Moissant ATCT/TRACON", "MSY_MVA_FUS5_2019"),
    FAAChart ("MWH", "Grant County ATCT/TRACON", "MWH_MVA_FUS3_2020"),
    FAAChart ("MWH", "Grant County ATCT/TRACON", "MWH_MVA_FUS5_2019"),
    FAAChart ("MYR", "Myrtle Beach ATCT/TRACON", "MYR_MVA_FUS3_2019"),
    FAAChart ("MYR", "Myrtle Beach ATCT/TRACON", "MYR_MVA_FUS5_2019"),
    FAAChart ("N90", "New York TRACON", "N90_MVA_FUS3_2020"),
    FAAChart ("N90", "New York TRACON", "N90_MVA_FUS5_2020"),
    FAAChart ("NCT", "Northern California TRACON", "NCT_MVA_FUS3_2019"),
    FAAChart ("NCT", "Northern California TRACON", "NCT_MVA_FUS5_2019"),
    FAAChart ("OKC", "Oklahoma City Will Rogers ATCT/TRACON", "OKC_MVA_FUS3_2019"),
    FAAChart ("OKC", "Oklahoma City Will Rogers ATCT/TRACON", "OKC_MVA_FUS5_2019"),
    FAAChart ("ORF", "Norfolk ATCT/TRACON", "ORF_MVA_FUS3_2020"),
    FAAChart ("ORF", "Norfolk ATCT/TRACON", "ORF_MVA_FUS5_2020"),
    FAAChart ("P31", "Pensacola TRACON", "P31_MVA_FUS3_2020"),
    FAAChart ("P31", "Pensacola TRACON", "P31_MVA_FUS5_2020"),
    FAAChart ("P50", "Phoenix TRACON", "P50_MVA_FUS3_2019"),
    FAAChart ("P50", "Phoenix TRACON", "P50_MVA_FUS5_2019"),
    FAAChart ("P80", "Portland TRACON", "P80_MVA_FUS5_2020"),
    FAAChart ("P80", "Portland TRACON", "P80_PDX_MVA_2020"),
    FAAChart ("P80", "Portland TRACON", "P80_QFL_MVA_2020"),
    FAAChart ("P80", "Portland TRACON", "P80_QMO_MVA_2020"),
    FAAChart ("PBI", "Palm Beach ATCT/TRACON", "PBI_MVA_FUS3_2018"),
    FAAChart ("PBI", "Palm Beach ATCT/TRACON", "PBI_MVA_FUS5_2018"),
    FAAChart ("PCT", "Potomac Consolidated TRACON", "PCT_MVA_FUS3_2019"),
    FAAChart ("PCT", "Potomac Consolidated TRACON", "PCT_MVA_FUS5_2019"),
    FAAChart ("PHL", "Philadelphia ATCT/TRACON", "PHL_MVA_FUS3_2020"),
    FAAChart ("PHL", "Philadelphia ATCT/TRACON", "PHL_MVA_FUS5_2020"),
    FAAChart ("PIA", "Peoria ATCT/TRACON", "PIA_MVA_FUS3_2020"),
    FAAChart ("PIT", "Pittsburgh ATCT/TRACON", "PIA_MVA_FUS5_2020"),
    FAAChart ("PSC", "Pasco ATCT/TRACON", "PSC_MVA_FUS3_2020"),
    FAAChart ("PSC", "Pasco ATCT/TRACON", "PSC_MVA_FUS5_2020"),
    FAAChart ("PVD", "Providence ATCT/TRACON", "PVD_MVA_FUS3_2019"),
    FAAChart ("PVD", "Providence ATCT/TRACON", "PVD_MVA_FUS5_2019"),
    FAAChart ("PWM", "Portland ATCT/TRACON", "PWM_MVA_FUS3_2020"),
    FAAChart ("PWM", "Portland ATCT/TRACON", "PWM_MVA_FUS5_2020"),
    FAAChart ("R90", "Omaha TRACON", "R90_MVA_FUS3_2019"),
    FAAChart ("R90", "Omaha TRACON", "R90_MVA_FUS5_2019"),
    FAAChart ("RDG", "Reading ATCT/TRACON", "RDG_MVA_FUS3_2019"),
    FAAChart ("RDU", "Raleigh ATCT/TRACON", "RDU_MVA_FUS3_2020"),
    FAAChart ("RDU", "Raleigh ATCT/TRACON", "RDU_MVA_FUS5_2020"),
    FAAChart ("RFD", "Rockford ATCT/TRACON", "RFD_MVA_FUS3_2019"),
    FAAChart ("RFD", "Rockford ATCT/TRACON", "RFD_MVA_FUS5_2019"),
    FAAChart ("ROA", "Roanoke ATCT/TRACON", "ROA_MVA_FUS3_2020"),
    FAAChart ("ROA", "Roanoke ATCT/TRACON", "ROA_MVA_FUS5_2020"),
    FAAChart ("ROC", "Rochester ATCT/TRACON", "ROC_MVA_FUS3_2019"),
    FAAChart ("ROC", "Rochester ATCT/TRACON", "ROC_MVA_FUS5_2019"),
    FAAChart ("ROW", "Roswell ATCT/TRACON", "ROW_MVA_FUS3_2019"),
    FAAChart ("ROW", "Roswell ATCT/TRACON", "ROW_MVA_FUS5_2019"),
    FAAChart ("RST", "Rochester ATCT/TRACON", "RST_MVA_FUS3_2020"),
    FAAChart ("RST", "Rochester ATCT/TRACON", "RST_MVA_FUS5_2020"),
    FAAChart ("RSW", "Ft. Myers FL ATCT/TRACON", "RSW_MVA_FUS3_2018"),
    FAAChart ("RSW", "Ft. Myers FL ATCT/TRACON", "RSW_MVA_FUS5_2020"),
    FAAChart ("S46", "Seattle TRACON", "S46_MVA_FUS3_2019"),
    FAAChart ("S46", "Seattle TRACON", "S46_MVA_FUS5_2019"),
    FAAChart ("S56", "Salt Lake City TRACON", "S56_MVA_FUS3_2019"),
    FAAChart ("S56", "Salt Lake City TRACON", "S56_MVA_FUS5_2019"),
    FAAChart ("SAT", "San Antonio Intnl ATCT/TRACON", "SAT_MVA_FUS3_2018"),
    FAAChart ("SAT", "San Antonio Intnl ATCT/TRACON", "SAT_MVA_FUS5_2020"),
    FAAChart ("SAV", "Savannah ATCT/TRACON", "SAV_LHW_MVA_2019"),
    FAAChart ("SAV", "Savannah ATCT/TRACON", "SAV_MVA_FUS3_2019"),
    FAAChart ("SAV", "Savannah ATCT/TRACON", "SAV_MVA_FUS5_2019"),
    FAAChart ("SBA", "Santa Barbara ATCT/TRACON", "SBA_MVA_FUS3_2018"),
    FAAChart ("SBA", "Santa Barbara ATCT/TRACON", "SBA_MVA_FUS5_2019"),
    FAAChart ("SBN", "South Bend ATCT/TRACON", "SBN_MVA_FUS3_2019"),
    FAAChart ("SBN", "South Bend ATCT/TRACON", "SBN_MVA_FUS5_2019"),
    FAAChart ("SCT", "Southern California TRACON", "SCT_MVA_FUS3_2020"),
    FAAChart ("SCT", "Southern California TRACON", "SCT_MVA_FUS5_2018"),
    FAAChart ("SDF", "Standiford ATCT/TRACON", "SDF_MVA_FUS3_2019"),
    FAAChart ("SDF", "Standiford ATCT/TRACON", "SDF_MVA_FUS5_2019"),
    FAAChart ("SGF", "Springfield ATCT/TRACON", "SGF_MVA_FUS3_2020"),
    FAAChart ("SGF", "Springfield ATCT/TRACON", "SGF_MVA_FUS5_2020"),
    FAAChart ("SHV", "Shreveport ATCT/TRACON", "SHV_MVA_FUS3_2020"),
    FAAChart ("SHV", "Shreveport ATCT/TRACON", "SHV_MVA_FUS5_2020"),
    FAAChart ("SPI", "Sprinfield ATCT/TRACON", "SPI_MVA_FUS3_2020"),
    FAAChart ("SPI", "Sprinfield ATCT/TRACON", "SPI_MVA_FUS5_2020"),
    FAAChart ("SUX", "Sioux City ATCT/TRACON", "SUX_MVA_FUS3_2021"),
    FAAChart ("SUX", "Sioux City ATCT/TRACON", "SUX_MVA_FUS5_2021"),
    FAAChart ("SYR", "Syracuse ATCT/TRACON", "SYR_MVA_FUS3_2020"),
    FAAChart ("SYR", "Syracuse ATCT/TRACON", "SYR_MVA_FUS5_2020"),
    FAAChart ("T75", "St. Louis TRACON", "T75_MVA_FUS3_2020"),
    FAAChart ("T75", "St. Louis TRACON", "T75_MVA_FUS5_2020"),
    FAAChart ("TLH", "Tallahassee ATCT/TRACON", "TLH_MVA_FUS3_2019"),
    FAAChart ("TLH", "Tallahassee ATCT/TRACON", "TLH_MVA_FUS5_2019"),
    FAAChart ("TOL", "Toledo ATCT/TRACON", "TOL_MVA_FUS3_2020"),
    FAAChart ("TOL", "Toledo ATCT/TRACON", "TOL_MVA_FUS5_2020"),
    FAAChart ("TPA", "Tampa ATCT/TRACON", "TPA_MVA_FUS3_2020"),
    FAAChart ("TPA", "Tampa ATCT/TRACON", "TPA_MVA_FUS5_2020"),
    FAAChart ("TRI", "Tri-City ATCT/TRACON", "TRI_MVA_FUS3_2019"),
    FAAChart ("TRI", "Tri-City ATCT/TRACON", "TRI_MVA_FUS5_2019"),
    FAAChart ("TUL", "Tulsa International ATCT/TRACON", "TUL_MVA_FUS3_2018"),
    FAAChart ("TUL", "Tulsa International ATCT/TRACON", "TUL_TUL TUL_MVA_FUS5_2018"),
    FAAChart ("TUL", "Tulsa International ATCT/TRACON", "TUL_QAF_MVA_2018"),
    FAAChart ("TWF", "Twin Falls ATCT/TRACON", "TWF_BYI_VOR_MVA_2020"),
    FAAChart ("TWF", "Twin Falls ATCT/TRACON", "TWF_TWF_VOR_MVA_2020"),
    FAAChart ("TYS", "Knoxville ATCT/TRACON", "TYS_MVA_FUS3_2019"),
    FAAChart ("TYS", "Knoxville ATCT/TRACON", "TYS_MVA_FUS5_2019"),
    FAAChart ("U90", "Tucson ATCT/TRACON", "U90_MVA_FUS3_2020"),
    FAAChart ("U90", "Tucson ATCT/TRACON", "U90_MVA_FUS5_2020"),
    FAAChart ("Y90", "Bradley ATCT/TRACON", "Y90_MVA_FUS3_2019"),
    FAAChart ("Y90", "Bradley ATCT/TRACON", "Y90_MVA_FUS5_2019"),
    FAAChart ("YNG", "Youngstown ATCT/TRACON", "YNG_MVA_FUS3_2018"),
    FAAChart ("YNG", "Youngstown ATCT/TRACON", "YNG_MVA_FUS5_2018"),
    FAAChart ("ZHN", "Honolulu Control Facility", "ZHN_HNL_ARS4_MVA_2019"),
    FAAChart ("ZHN", "Honolulu Control Facility", "ZHN_HNL_ASR9_MVA_2019"),
    FAAChart ("ZHN", "Honolulu Control Facility", "ZHN_ITO_ASR8_MVA_2019"),
    FAAChart ("ZHN", "Honolulu Control Facility", "ZHN_LIH_MVA_2019"),
    FAAChart ("ZHN", "Honolulu Control Facility", "ZHN_MVA_FUS3_2020"),
    FAAChart ("ZHN", "Honolulu Control Facility", "ZHN_OGG_MVA_2018"),
    FAAChart ("ZLC", "Salt Lake City ARTCC", "ZLC_BZN_MVA_2020"),
    FAAChart ("ZLC", "Salt Lake City ARTCC", "ZLC_CDC_MVA_2020"),
    FAAChart ("ZLC", "Salt Lake City ARTCC", "ZLC_GPI_MVA_2020"),
    FAAChart ("ZLC", "Salt Lake City ARTCC", "ZLC_JAC_MVA_2020"),
    FAAChart ("ZLC", "Salt Lake City ARTCC", "ZLC_QWA_MVA_2020"),
    FAAChart ("ZLC", "Salt Lake City ARTCC", "ZLC_RKS_MVA_2020"),
    FAAChart ("ZOA", "Oakland ARTCC", "ZOA_QMV_MVA_2018"),
    FAAChart ("ZOA", "Oakland ARTCC", "ZOA_RBL_MVA_2018"),
    FAAChart ("ZSU", "San Juan CERAP", "ZSU_BQN_MVA_2018"),
    FAAChart ("ZSU", "San Juan CERAP", "ZSU_MVA_MULTI_2018"),
    FAAChart ("ZSU", "San Juan CERAP", "ZSU_PICO_MVA_2020"),
    FAAChart ("ZSU", "San Juan CERAP", "ZSU_PSR_MVA_2018"),
    FAAChart ("ZSU", "San Juan CERAP", "ZSU_SJU_MVA_2018"),
    FAAChart ("ZSU", "San Juan CERAP", "ZSU_SSR7_MVA_2018"),
    FAAChart ("ZSU", "San Juan CERAP", "ZSU_STT_MVA_2018"),
    FAAChart ("ZUA", "Guam ARTCC", "ZUA_GUAM_MVA_2020"),
    FAAChart ("ZUA", "Guam ARTCC", "ZUA_MVA_CENRAP_2020"),
)

// EOF

        